---
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: ((david.slack-tag))

resources:
- name: src
  type: git
  source:
    # uri: git@github.com:davidwalter0/docker-remote-tunnel.git
    uri: https://github.com/davidwalter0/docker-remote-tunnel
    # uri: git@github.com:ruanbekker/docker-remote-tunnel.git
    branch: master
    # private_key: ((david.github-private-key))

########## - name: docker-remote-tunnel-image
##########   type: docker-image
##########   source:
##########     repository: davidwalter/docker-remote-tunnel
##########     tag: test
##########     username: ((david.dockerhub-user))
##########     password: ((david.dockerhub-password))

- name: alert
  type: slack-notification
  source:
    url: ((david.slack-notification-url))

jobs:
  - name: job
    public: true
    plan:
      - task: simple-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
              tag: ((david.busybox-tag))
          run:
            path: /bin/sh
            args:
            - -c
            - |
              date
              busybox | head -1
              date
            # args: ["Hello, world!"]
            # - 'busybox | head -1'
            # # args: ["Hello, world!"]

  - name: task-reuse
    serial: true
    plan:
      - get: src
        trigger: true
      - task: task-reuse
        params:
          BUSYBOX_TAG: ((david.busybox-tag))
        file: src/ci/task/task01.yml
        on_failure:
          do:
            - put: alert
              params:
                text: ":fire: <https://ci.comcast.net/teams/viper-veg/pipelines/coral/jobs/deploy-qa/builds/latest> Deployment Failed :fire:"

  ########## - name: test
  ##########   plan:
  ##########   - get: docker-remote-tunnel-image
  ##########     # passed: [build-cached-image]
  ##########     # trigger: true
  ##########   - get: src
  ##########     # passed: [build-cached-image]
  ##########   - task: run-tests
  ##########     image: docker-remote-tunnel-image
  ##########     config:
  ##########       platform: linux
  ##########       inputs:
  ##########       - name: src
  ##########       run:
  ##########         dir: src
  ##########         path: sh
  ##########         args:
  ##########         - /usr/bin/docker-tunnel
  ##########         - --help

  ##########     on_failure:
  ##########       put: alert
  ##########       params:
  ##########         # channel: '#system_events'
  ##########         username: 'concourse'
  ##########         icon_emoji: ':concourse:'
  ##########         silent: true
  ##########         text: |
  ##########             *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* ($BUILD_NAME) FAILED - Testing image failure
  ##########             https://ci.domain.com/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
  ##########     on_success:
  ##########       put: alert
  ##########       params:
  ##########         # channel: '#system_events'
  ##########         username: 'concourse'
  ##########         icon_emoji: ':concourse:'
  ##########         silent: true
  ##########         text: |
  ##########             *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* ($BUILD_NAME) SUCCESS - Testing image Succeeded
  ##########             https://ci.domain.com/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

########## - name: build-cached-image
##########   plan:
##########   - get: src
##########     trigger: true
##########   - task: build-cached-image-workspace
##########     config:
##########       platform: linux
##########       image_resource:
##########         type: docker-image
##########         source:
##########           repository: davidwalter/build-tools

##########       outputs:
##########       - name: workspace
##########       inputs:
##########       - name: src

##########       run:
##########         path: /bin/sh
##########         args:
##########         - -c
##########         - |
##########           #!/bin/sh
##########           output_dir=workspace

##########           cat << EOF > "${output_dir}/Dockerfile"
##########           FROM alpine

##########           ADD src /tmp/src
##########           RUN mv /tmp/src/docker-tunnel /usr/bin/docker-tunnel
##########           RUN apk --no-cache add screen docker openssl openssh-client apache2-utils
##########           RUN /usr/bin/docker-tunnel -h
##########           RUN rm -rf /tmp/src
##########           EOF

##########           cp -R ./src "${output_dir}/src"

##########   - put: docker-remote-tunnel-image
##########     params:
##########       build: workspace

##########     on_failure:
##########       put: alert
##########       params:
##########         channel: '#system_events'
##########         username: 'concourse'
##########         icon_emoji: ':concourse:'
##########         silent: true
##########         text: |
##########             *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* ($BUILD_NAME) FAILED to build image
##########             https://ci.domain.com/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
##########     on_success:
##########       put: alert
##########       params:
##########         channel: '#system_events'
##########         username: 'concourse'
##########         icon_emoji: ':concourse:'
##########         silent: true
##########         text: |
##########             *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* ($BUILD_NAME) SUCCESS - Image has been published
##########             https://ci.domain.com/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

########## - name: test
##########   plan:
##########   - get: docker-remote-tunnel-image
##########     passed: [build-cached-image]
##########     # trigger: true
##########   - get: src
##########     passed: [build-cached-image]
##########   - task: run-tests
##########     image: docker-remote-tunnel-image
##########     config:
##########       platform: linux
##########       inputs:
##########       - name: src
##########       run:
##########         dir: src
##########         path: sh
##########         args:
##########         - /usr/bin/docker-tunnel
##########         - --help

##########     on_failure:
##########       put: alert
##########       params:
##########         # channel: '#system_events'
##########         username: 'concourse'
##########         icon_emoji: ':concourse:'
##########         silent: true
##########         text: |
##########             *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* ($BUILD_NAME) FAILED - Testing image failure
##########             https://ci.domain.com/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
##########     on_success:
##########       put: alert
##########       params:
##########         # channel: '#system_events'
##########         username: 'concourse'
##########         icon_emoji: ':concourse:'
##########         silent: true
##########         text: |
##########             *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* ($BUILD_NAME) SUCCESS - Testing image Succeeded
##########             https://ci.domain.com/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
