---
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: ((david.slack-tag))

resources:
- name: git-repo
  type: git
  source:
    uri: git@github.com:davidwalter0/docker-remote-tunnel.git
    # uri: git@github.com:ruanbekker/docker-remote-tunnel.git
    branch: davidwalter0-patch-1
    private_key: ((david.github_private_key))

- name: docker-remote-tunnel-image
  type: docker-image
  source:
    repository: davidwalter/docker-remote-tunnel
    tag: test
    username: ((david.dockerhub_user))
    password: ((david.dockerhub_password))

- name: alert
  type: slack-notification
  source:
    url: ((david.slack-notification-url))

jobs:
  - name: job
    public: true
    plan:
      - task: simple-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
              tag: ((david.busybox-tag))
          run:
            path: /bin/sh
            args:
            - -c
            - |
              date
              busybox | head -1
              date
            # args: ["Hello, world!"]
            # - 'busybox | head -1'
            # # args: ["Hello, world!"]

  - name: task-reuse
    serial: true
    plan:
      - task: task-reuse
        params:
          CONTEXT: smoke
          TOKEN: ((david.token))
          GHE_TOKEN: ((david.github-access-token))
        file: ci/task01.yaml
        on_failure:
          do:
            - put: alert
              params:
                text: ":fire: <https://ci.comcast.net/teams/viper-veg/pipelines/coral/jobs/deploy-qa/builds/latest> Deployment Failed :fire:"
